import { DemoStyle } from "./types";

export const DEMO_STYLES: DemoStyle[] = [
  {
    id: "scandinavian",
    name: "Scandinavian",
    tagline: "Bright, airy, and warm minimalism",
    description: "Features neutral tones, light wood accents, clean lines, cozy sheepskin layers, and rich natural greenery.",
    originalUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1200",
    reimaginedUrl: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?q=80&w=1200",
    bgColor: "bg-slate-50",
    textColor: "text-slate-800",
    borderColor: "border-slate-200",
    hotspots: [
      {
        id: "scand-sofa",
        name: "NORDIC Custom Fabric 3-Seater Sofa",
        price: "$899.00",
        store: "Article",
        url: "https://www.article.com",
        description: "A tailored gray linen sofa featuring a low profile, button-tufted cushions, and solid oak tapered legs.",
        x: 62,
        y: 65,
      },
      {
        id: "scand-mirror",
        name: "SÖDER Frameless Round Wall Mirror",
        price: "$120.00",
        store: "IKEA",
        url: "https://www.ikea.com",
        description: "A large 80cm circular mirror with a slim birch-veneer trim, expanding light throughout the room.",
        x: 48,
        y: 25,
      },
      {
        id: "scand-rug",
        name: "FJÄRDING Handwoven Cream Wool Rug",
        price: "$340.00",
        store: "West Elm",
        url: "https://www.westelm.com",
        description: "Thick plush pile rug handwoven in India from 100% natural, un-dyed pure sheep wool.",
        x: 52,
        y: 85,
      }
    ]
  },
  {
    id: "midcentury",
    name: "Mid-Century Modern",
    tagline: "Retro organic shapes & warm wood tones",
    description: "Combines tapered walnut legs, vibrant accent hues, rich geometric patterns, and classic statement light fixtures.",
    originalUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1200",
    reimaginedUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1200",
    bgColor: "bg-amber-50/60",
    textColor: "text-amber-950",
    borderColor: "border-amber-200",
    hotspots: [
      {
        id: "mcm-chair",
        name: "Retro Forest Green Velvet Lounge Chair",
        price: "$450.00",
        store: "Joybird",
        url: "https://www.joybird.com",
        description: "Elegantly molded plywood frame with thick foam backing upholstered in premium emerald green velvet.",
        x: 32,
        y: 68,
      },
      {
        id: "mcm-credenza",
        name: "Hutchinson Solid Walnut Media Console",
        price: "$1,199.00",
        store: "West Elm",
        url: "https://www.westelm.com",
        description: "Beautiful walnut credenza featuring mid-century style tapered legs and clean sliding slatted doors.",
        x: 75,
        y: 58,
      },
      {
        id: "mcm-pendant",
        name: "Apollo Brass Pendant Orb Light",
        price: "$180.00",
        store: "Rejuvenation",
        url: "https://www.rejuvenation.com",
        description: "Polished brass finish globe lamp that hangs gracefully to provide a focused warm glow.",
        x: 50,
        y: 18,
      }
    ]
  },
  {
    id: "bohemian",
    name: "Bohemian",
    tagline: "Eclectic textures, plants, and natural fiber",
    description: "Layered cozy spaces characterized by abundant hanging ivy, hand-tied macrames, rattan seating, and global prints.",
    originalUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1200",
    reimaginedUrl: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?q=80&w=1200",
    bgColor: "bg-orange-50/40",
    textColor: "text-orange-950",
    borderColor: "border-orange-200",
    hotspots: [
      {
        id: "boho-macrame",
        name: "Zuri Handwoven Cotton Macrame Wall Tapestry",
        price: "$65.00",
        store: "Etsy",
        url: "https://www.etsy.com",
        description: "Woven by local craftsmen using 100% organic cotton cord mounted on a natural birch wood dowel.",
        x: 50,
        y: 30,
      },
      {
        id: "boho-rattan",
        name: "Marrakech Natural Rattan Accent Chair",
        price: "$220.00",
        store: "World Market",
        url: "https://www.worldmarket.com",
        description: "Artisanal hand-shaped natural rattan frame, lightweight and incredibly comfortable with a floor cushion.",
        x: 25,
        y: 70,
      },
      {
        id: "boho-monstera",
        name: "Split-Leaf Monstera Deliciosa",
        price: "$75.00",
        store: "The Sill",
        url: "https://www.thesill.com",
        description: "Gorgeous live indoor plant housed in a matching handcrafted raw terracotta container.",
        x: 80,
        y: 60,
      }
    ]
  },
  {
    id: "japandi",
    name: "Japandi",
    tagline: "Serene union of Japanese & Scandinavian simplicity",
    description: "Focuses on clean minimalism, low-profile oak furniture, earth-toned linens, warm paper lamps, and raw-edge organic tables.",
    originalUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1200",
    reimaginedUrl: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?q=80&w=1200",
    bgColor: "bg-neutral-50",
    textColor: "text-neutral-800",
    borderColor: "border-neutral-200",
    hotspots: [
      {
        id: "japandi-sofa",
        name: "Kyoto Low-Profile Oatmeal Linen Sofa",
        price: "$1,450.00",
        store: "Muji",
        url: "https://www.muji.com",
        description: "Solid natural white oak frame with thick supportive cushions upholstered in organic washed linen.",
        x: 55,
        y: 65,
      },
      {
        id: "japandi-vases",
        name: "Wabi-Sabi Matte Ceramic Vessels (Set of 3)",
        price: "$85.00",
        store: "Crate & Barrel",
        url: "https://www.crateandbarrel.com",
        description: "Three handcrafted asymmetrical clay vases in sandy matte finishes, perfect for dried stems.",
        x: 25,
        y: 55,
      },
      {
        id: "japandi-lamp",
        name: "Akari-Style Rice Paper Floor Lantern",
        price: "$110.00",
        store: "Muji",
        url: "https://www.muji.com",
        description: "Delicate mulberry bark paper shade on thin black wire tripod legs, radiating cozy diffused warm light.",
        x: 85,
        y: 45,
      }
    ]
  },
  {
    id: "industrial",
    name: "Industrial",
    tagline: "Bold textures of exposed brick and dark metal",
    description: "Brings industrial loft character with raw brick, piping fixtures, rustic timber shelving, and luxurious leather seatings.",
    originalUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1200",
    reimaginedUrl: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?q=80&w=1200",
    bgColor: "bg-zinc-50",
    textColor: "text-zinc-800",
    borderColor: "border-zinc-200",
    hotspots: [
      {
        id: "ind-sofa",
        name: "Chesterfield Cognac Full-Aniline Leather Sofa",
        price: "$1,899.00",
        store: "CB2",
        url: "https://www.cb2.com",
        description: "Plush top-grain cognac brown leather with deep hand-tufted details and iron base structure.",
        x: 50,
        y: 65,
      },
      {
        id: "ind-shelf",
        name: "Foundry Pipe & Reclaimed Wood Bookshelf",
        price: "$480.00",
        store: "Restoration Hardware",
        url: "https://www.restorationhardware.com",
        description: "Six open tiers of rustic pine planks supported by sturdy dark-finish structural steel plumbing pipes.",
        x: 85,
        y: 40,
      },
      {
        id: "ind-bulb",
        name: "Steampunk Dimmable Edison Floor Beacon",
        price: "$160.00",
        store: "Wayfair",
        url: "https://www.wayfair.com",
        description: "Heavy iron base holding three exposed amber-filament LED Edison bulbs on rustic pipe elbows.",
        x: 15,
        y: 50,
      }
    ]
  }
];
